# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length > 0 %}
    ### New Contributors ❤️
    {% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
        * @{{ contributor.username }} made their first contribution
            {%- if contributor.pr_number %} in #{{ contributor.pr_number }}{%- endif %}
    {% endfor %}
{% endif %}\
"""

trim = true
render_always = true
postprocessors = []

[git]
ignore_tags = "python-.*"
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/b-rowan/hass-asic-rs/issues/${2}))"},
#    { pattern = '.*', replace_command = 'typos --write-changes -' },
]
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat|^feature", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix|^bug", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^doc", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf", group = "<!-- 4 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^style", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test", group = "<!-- 6 -->🧪 Testing" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore: format, fix lints|^chore: Format", skip = true },
    { message = "^version", skip = true },
    { message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
    { body = ".*security", group = "<!-- 8 -->🛡️ Security" },
    { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
    { message = ".*", group = "<!-- 10 -->💼 Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
link_parsers = []
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false

[remote.github]
owner = "b-rowan"
repo = "hass-asic-rs"

[bump]
features_always_bump_minor = false
breaking_always_bump_major = false
initial_tag = "0.1.0"
