services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ha_config:/config
      - ./custom_components:/config/custom_components:ro
      - ./.devcontainer/homeassistant-configuration.yaml:/config/configuration.yaml:ro
    network_mode: host
    restart: unless-stopped

volumes:
  ha_config:
